/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.balic.zavrsnirad.view;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Kira
 */
public class Izbornik extends javax.swing.JFrame {

    /**
     * Creates new form Izbornik
     */
    public Izbornik() {
        initComponents();
        setTitle("Beauty salon");
        
        
    
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlZaposlenik = new javax.swing.JPanel();
        indZaposlenik = new javax.swing.JPanel();
        lblZaposlenik = new javax.swing.JLabel();
        pnlPocetna = new javax.swing.JPanel();
        indPocetna = new javax.swing.JPanel();
        lblPocetna = new javax.swing.JLabel();
        pnlTermin = new javax.swing.JPanel();
        indTermin = new javax.swing.JPanel();
        lblTermin = new javax.swing.JLabel();
        pnlUsluga = new javax.swing.JPanel();
        indUsluga = new javax.swing.JPanel();
        lblUsluga = new javax.swing.JLabel();
        pnlPostavke = new javax.swing.JPanel();
        indPostavke = new javax.swing.JPanel();
        lblPostavke = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNaslovnaSlika = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(23, 35, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlZaposlenik.setBackground(new java.awt.Color(23, 35, 51));
        pnlZaposlenik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlZaposlenikMousePressed(evt);
            }
        });

        indZaposlenik.setPreferredSize(new java.awt.Dimension(5, 43));

        javax.swing.GroupLayout indZaposlenikLayout = new javax.swing.GroupLayout(indZaposlenik);
        indZaposlenik.setLayout(indZaposlenikLayout);
        indZaposlenikLayout.setHorizontalGroup(
            indZaposlenikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        indZaposlenikLayout.setVerticalGroup(
            indZaposlenikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblZaposlenik.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblZaposlenik.setForeground(new java.awt.Color(255, 255, 255));
        lblZaposlenik.setText("Zaposlenik");
        lblZaposlenik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblZaposlenikMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlZaposlenikLayout = new javax.swing.GroupLayout(pnlZaposlenik);
        pnlZaposlenik.setLayout(pnlZaposlenikLayout);
        pnlZaposlenikLayout.setHorizontalGroup(
            pnlZaposlenikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlZaposlenikLayout.createSequentialGroup()
                .addComponent(indZaposlenik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblZaposlenik, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );
        pnlZaposlenikLayout.setVerticalGroup(
            pnlZaposlenikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indZaposlenik, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(pnlZaposlenikLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblZaposlenik, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(pnlZaposlenik, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, -1, -1));

        pnlPocetna.setBackground(new java.awt.Color(41, 57, 80));
        pnlPocetna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlPocetnaMousePressed(evt);
            }
        });

        indPocetna.setPreferredSize(new java.awt.Dimension(5, 43));

        javax.swing.GroupLayout indPocetnaLayout = new javax.swing.GroupLayout(indPocetna);
        indPocetna.setLayout(indPocetnaLayout);
        indPocetnaLayout.setHorizontalGroup(
            indPocetnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        indPocetnaLayout.setVerticalGroup(
            indPocetnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        lblPocetna.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPocetna.setForeground(new java.awt.Color(255, 255, 255));
        lblPocetna.setText("Početna");
        lblPocetna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblPocetnaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlPocetnaLayout = new javax.swing.GroupLayout(pnlPocetna);
        pnlPocetna.setLayout(pnlPocetnaLayout);
        pnlPocetnaLayout.setHorizontalGroup(
            pnlPocetnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPocetnaLayout.createSequentialGroup()
                .addComponent(indPocetna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 134, Short.MAX_VALUE))
            .addGroup(pnlPocetnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlPocetnaLayout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(lblPocetna, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );
        pnlPocetnaLayout.setVerticalGroup(
            pnlPocetnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indPocetna, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(pnlPocetnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlPocetnaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblPocetna, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel1.add(pnlPocetna, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        pnlTermin.setBackground(new java.awt.Color(23, 35, 51));
        pnlTermin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlTerminMousePressed(evt);
            }
        });

        indTermin.setPreferredSize(new java.awt.Dimension(5, 43));

        javax.swing.GroupLayout indTerminLayout = new javax.swing.GroupLayout(indTermin);
        indTermin.setLayout(indTerminLayout);
        indTerminLayout.setHorizontalGroup(
            indTerminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        indTerminLayout.setVerticalGroup(
            indTerminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblTermin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTermin.setForeground(new java.awt.Color(255, 255, 255));
        lblTermin.setText("Termin");
        lblTermin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblTerminMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlTerminLayout = new javax.swing.GroupLayout(pnlTermin);
        pnlTermin.setLayout(pnlTerminLayout);
        pnlTerminLayout.setHorizontalGroup(
            pnlTerminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTerminLayout.createSequentialGroup()
                .addComponent(indTermin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTermin, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );
        pnlTerminLayout.setVerticalGroup(
            pnlTerminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indTermin, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(pnlTerminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTermin, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(pnlTermin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        pnlUsluga.setBackground(new java.awt.Color(23, 35, 51));
        pnlUsluga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlUslugaMousePressed(evt);
            }
        });

        indUsluga.setPreferredSize(new java.awt.Dimension(5, 43));

        javax.swing.GroupLayout indUslugaLayout = new javax.swing.GroupLayout(indUsluga);
        indUsluga.setLayout(indUslugaLayout);
        indUslugaLayout.setHorizontalGroup(
            indUslugaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        indUslugaLayout.setVerticalGroup(
            indUslugaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblUsluga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsluga.setForeground(new java.awt.Color(255, 255, 255));
        lblUsluga.setText("Usluga");
        lblUsluga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblUslugaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlUslugaLayout = new javax.swing.GroupLayout(pnlUsluga);
        pnlUsluga.setLayout(pnlUslugaLayout);
        pnlUslugaLayout.setHorizontalGroup(
            pnlUslugaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUslugaLayout.createSequentialGroup()
                .addComponent(indUsluga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUsluga, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );
        pnlUslugaLayout.setVerticalGroup(
            pnlUslugaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indUsluga, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(pnlUslugaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsluga, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(pnlUsluga, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        pnlPostavke.setBackground(new java.awt.Color(23, 35, 51));
        pnlPostavke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlPostavkeMousePressed(evt);
            }
        });

        indPostavke.setPreferredSize(new java.awt.Dimension(5, 43));

        javax.swing.GroupLayout indPostavkeLayout = new javax.swing.GroupLayout(indPostavke);
        indPostavke.setLayout(indPostavkeLayout);
        indPostavkeLayout.setHorizontalGroup(
            indPostavkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        indPostavkeLayout.setVerticalGroup(
            indPostavkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblPostavke.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPostavke.setForeground(new java.awt.Color(255, 255, 255));
        lblPostavke.setText("Klijenti");

        javax.swing.GroupLayout pnlPostavkeLayout = new javax.swing.GroupLayout(pnlPostavke);
        pnlPostavke.setLayout(pnlPostavkeLayout);
        pnlPostavkeLayout.setHorizontalGroup(
            pnlPostavkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPostavkeLayout.createSequentialGroup()
                .addComponent(indPostavke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPostavke, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );
        pnlPostavkeLayout.setVerticalGroup(
            pnlPostavkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indPostavke, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(pnlPostavkeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPostavke, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(pnlPostavke, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 610));

        jPanel2.setBackground(new java.awt.Color(71, 120, 197));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 930, 60));

        lblNaslovnaSlika.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kira\\Desktop\\naslovna1.jpg")); // NOI18N
        getContentPane().add(lblNaslovnaSlika, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 930, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblPocetnaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPocetnaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPocetnaMousePressed

    private void lblTerminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTerminMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTerminMousePressed

    private void lblUslugaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUslugaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUslugaMousePressed

    private void lblZaposlenikMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblZaposlenikMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblZaposlenikMousePressed

    private void pnlPocetnaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPocetnaMousePressed
        // TODO add your handling code here:
        
        setColor(pnlPocetna);
        indPocetna.setOpaque(true);
        resetColor(new JPanel[] {pnlTermin, pnlUsluga, pnlZaposlenik, pnlPostavke}, new JPanel[]{indPostavke, indTermin, indUsluga, indZaposlenik});
    }//GEN-LAST:event_pnlPocetnaMousePressed

    private void pnlTerminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTerminMousePressed
        // TODO add your handling code here:
        setColor(pnlTermin);
        indTermin.setOpaque(true);
        resetColor(new JPanel[] {pnlPocetna, pnlUsluga, pnlZaposlenik, pnlPostavke}, new JPanel[]{indPostavke, indPocetna, indUsluga, indZaposlenik});
    }//GEN-LAST:event_pnlTerminMousePressed

    private void pnlUslugaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUslugaMousePressed
        // TODO add your handling code here:
        setColor(pnlUsluga);
        indUsluga.setOpaque(true);
        resetColor(new JPanel[] {pnlTermin, pnlPocetna, pnlZaposlenik, pnlPostavke}, new JPanel[]{indPostavke, indTermin, indPocetna, indZaposlenik});
    }//GEN-LAST:event_pnlUslugaMousePressed

    private void pnlZaposlenikMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlZaposlenikMousePressed
        // TODO add your handling code here:
        setColor(pnlZaposlenik);
        indZaposlenik.setOpaque(true);
        resetColor(new JPanel[] {pnlTermin, pnlUsluga, pnlPocetna, pnlPostavke}, new JPanel[]{indPostavke, indTermin, indUsluga, indZaposlenik});
    }//GEN-LAST:event_pnlZaposlenikMousePressed

    private void pnlPostavkeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPostavkeMousePressed
        // TODO add your handling code here:
        setColor(pnlPostavke);
        indPostavke.setOpaque(true);
        resetColor(new JPanel[] {pnlTermin, pnlUsluga, pnlPocetna, pnlPocetna}, new JPanel[]{indPocetna, indTermin, indUsluga, indZaposlenik});
    }//GEN-LAST:event_pnlPostavkeMousePressed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel indPocetna;
    private javax.swing.JPanel indPostavke;
    private javax.swing.JPanel indTermin;
    private javax.swing.JPanel indUsluga;
    private javax.swing.JPanel indZaposlenik;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNaslovnaSlika;
    private javax.swing.JLabel lblPocetna;
    private javax.swing.JLabel lblPostavke;
    private javax.swing.JLabel lblTermin;
    private javax.swing.JLabel lblUsluga;
    private javax.swing.JLabel lblZaposlenik;
    private javax.swing.JPanel pnlPocetna;
    private javax.swing.JPanel pnlPostavke;
    private javax.swing.JPanel pnlTermin;
    private javax.swing.JPanel pnlUsluga;
    private javax.swing.JPanel pnlZaposlenik;
    // End of variables declaration//GEN-END:variables

    
    
    private void setColor(JPanel panel) {
        
        panel.setBackground(new Color(41,57,80));
    }
    
    private void resetColor(JPanel [] panel, JPanel [] indicators) {
        
        for(int i=0; i<panel.length; i++){
            panel[i].setBackground(new Color(23,35,51));
        }
        for(int i=0; i<indicators.length; i++){
            indicators[i].setOpaque(false);
        }
    }
    
}
